### ISSUE TITLE
Performance decreases very much

### ISSUE THREAD

**Issue by HDScurox** [mcailleaux/WFRP4-FoundryVTT-wfrp4e-npc-generator#1]
When I use this module, the whole foundryVTT decreases to slow mode. I'm using FVTT on The Forge.

**Comment by mcailleaux** [comment]
Can you tell me witch version of the module is in cause ?

currently I have an initial caching data issus on initialization on the 1.2.0, I a working on it

**Comment by mcailleaux** [comment]
Can you test with the 1.2.1 patch ?
