### ISSUE TITLE
Foundry 0.8n Compatibility

### ISSUE THREAD

**Issue by bluetardis** [mcailleaux/WFRP4-FoundryVTT-wfrp4e-npc-generator#10]
I haven't updated yet but will be bringing up a test system/world next week.
Any known issues (eg should we wait for a release) or just log bug reports as we find them.

I can see you have done some work but was waiting for a release vs dev code.

[Really love the functionality of the module in 0.7.10 and don't want to lose it.]

**Comment by mcailleaux** [comment]
Hi, thank u for your suport :), The core by Moo man and the french translate module are done and stable so I can work on the 0.8 compatibility  know.

**Comment by bluetardis** [comment]
Super News!

lmk if you need help testing

**Comment by bluetardis** [comment]
I can see you did updates for 0.8.  Is it ok to use or should I wait.  Will be playing in English.

**Comment by mcailleaux** [comment]
Yes its ok to use but their is a bug with unmigrated compendium Items (from module not compatible with new core system). If its happened you can just disable those modules or delete uncompatible compendium. I will make a patch ASAP to just ignore uncompatible compendium without crash

**Comment by mcailleaux** [comment]
The 2.0.1 patches ignore uncompatible compendium
