### ISSUE TITLE
Erreur "type" not present in ItemData

### ISSUE THREAD

**Issue by Obiatn** [mcailleaux/WFRP4-FoundryVTT-wfrp4e-npc-generator#12]
Salut !
Sur un Foundry 0.8.8, un monde WFRP4 4.0.6 à jour avec ton module à jour en 2.0.0, impossible de passer l'étape d'initialisation des compendiums dès le 1er chargement : 

![image](https://user-images.githubusercontent.com/35995302/128606217-329cedd7-81cf-4f96-82e9-9d98d3af361f.png)

**Comment by mcailleaux** [comment]
La version 2.0.1 ignore les compendiums non compatible/migré
