### ISSUE TITLE
High-level career

### ISSUE THREAD

**Issue by Asimovian68** [mcailleaux/WFRP4-FoundryVTT-wfrp4e-npc-generator#15]
When I try an NPC with a high-level career, it appears to stall. I know it's supposed to generate all the skills, etc., for each career level, but how long is it supposed to take?

**Comment by mcailleaux** [comment]
Hi, can you give me : 

- foundry version
- system version
- C7 core module version

Have you others unofficial modules which includes careers or skills like Human mankind or Ogre kingdom ?

Have you an error into the console ? (F12)

Choose a single high level career is supposed to give you all the skills at +level*5

**Comment by Asimovian68** [comment]
OK I had an unofficial character module installed - Dwarf Empire. Upon removing it, your NPC Generator works fine. Thanks so much for your help!
