### ISSUE TITLE
PNJ n'apparait pas dans l'onglet Personnages

### ISSUE THREAD

**Issue by Obiatn** [mcailleaux/WFRP4-FoundryVTT-wfrp4e-npc-generator#2]
Foundry 0.7.9
Warhammer 3.5.1

Lors de la création d'un PNJ, le bouton "Carrière Aléatoire Humain" ne produit rien (même pas une erreur dans la console)
A l'issue de la création terminée, avec le choix de l'équipement Race + Carrière + Argent, l'erreur suivante dans la console : 

![image](https://user-images.githubusercontent.com/35995302/116529409-37108380-a8dd-11eb-89f8-be096f09146a.png)

**Comment by Obiatn** [comment]
Puis, en recommençant, mais en décochant l'équipement Race + Carrière + Argent, une autre erreur dans la console : 

![image](https://user-images.githubusercontent.com/35995302/116530367-3cba9900-a8de-11eb-94cb-8408e3b986ea.png)

**Comment by mcailleaux** [comment]
Corrigé avec le patch 1.2.1
