### ISSUE TITLE
Equipping items

### ISSUE THREAD

**Issue by simulacrum-1** [mcailleaux/WFRP4-FoundryVTT-wfrp4e-npc-generator#5]
I was just playing with it today it's brilliant. Nice work!
Just a suggestion it would be amazing if equipment/armour was worn by default. Same for weapons – though I imagine that may not be possible due to choices.

**Comment by mcailleaux** [comment]
I will try to do it for next release

**Comment by mcailleaux** [comment]
Resolved in the 1.3.0 version
